site_name: Portfólio 2 e 3 de Inteligência Artificial

theme:
   name: material 
   palette:
    - scheme: default
      toggle: 
         icon: material/toggle-switch-off-outline
         name: Dark mode
      primary: blue
    - scheme: slate
      toggle:
         icon: material/toggle-switch
         name: Light mode

nav:
  - Impressões gerais: index.md
  - Portfólio 2:
    - Agentes de soluções de problemas: problem_solution_agent.md
    - Problemas de malha aberta e de malha fechada: open-closed-problems.md
    - Algoritmos de busca: search-algoritms.md
    - Funções Heurísticas: heuristic_functions.md
    - Busca em ambientes complexos: complex_search.md
    - Algoritmos genéticos: genetic_algoritms.md
    - Conclusão: conclusion_first.md
  - Portfólio 3:
    - Representação Atômica vs. Fatorada: atomic_vs_factored.md
    - Definindo Problemas de Satisfação de Condições: satisfaction_problems.md
    - Algoritmos: CSP_algorithms.md
    - Estrutura de problemas: index.md
    - Conclusão: conclusion_second.md
